### ISSUE TITLE
#811 breaks sealed workflow execution: startRun credential test fails with Cannot find module 'smthrs/jsx-dev-runtime'

### ISSUE THREAD

**Issue by aviggiano** [monad-developers/ultrafuzz#837]
## Symptom

`startRun forwards cloud provider credentials through the Smithers environment filter` (runtime.test.ts) fails deterministically on main with:

```
Cannot find module 'smthrs/jsx-dev-runtime' from 'ultrafuzz-sealed-module:<run>/smithers/execution-snapshots/<hash>/.smithers/workflows/ultrafuzz-cloud-environment.tsx'
```

Red in main CI run 32793876385 (Node.js 24 integration shard 4/4). Reproduces 3/3 in isolation on a clean origin/main worktree.

## Bisect

`git bisect` between a6341659 (#807 squash, good) and main HEAD names **8caf159f (#811 "Preserve fresh operator runner execution authority") as the first bad commit**.

## Observations

- smthrs 0.34.0 exports both `./jsx-runtime` and `./jsx-dev-runtime`, so this is a resolution/confinement failure, not a missing export.
- The failing workflow tsx was loaded through the `ultrafuzz-sealed-module` namespace (the confinement plugin's descriptor-alias path), and the bare `smthrs/jsx-dev-runtime` import from that namespace then fails to resolve.
- #811 newly sets `ULTRAFUZZ_BUN_MODULE_CONFINEMENT` (rooted at the operator controller) on the operator runner environment (smithers.ts:4010), while the per-run child confinement is rooted at the execution snapshot (workflow-integrity.ts:1445) — the interaction between the inherited operator value and the run-scoped value is the prime suspect.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by aviggiano** [comment]
Correction to this issue's bisect attribution: the regression is **#794 (51ac3ffc)**, not #811. The bisect's 'good' endpoint (a6341659) was never actually green — its CI run was cancelled by a superseding push, and the failure reproduces at a6341659 in a clean worktree. CI history confirms: shard 4/4 green at fc7d10a1 (#779), red at 51ac3ffc and every completed run since. #794's own regression test missed it because its probe ran with cwd inside the sealed root, which is exactly the fallback path Bun takes for plugin-namespace imports. Root cause and fix in PR #844.

**Comment by aviggiano** [comment]
Fixed on main by #841 (file-namespace descriptor loading with canonical validation — same root-cause diagnosis as PR #844, which is closed as superseded). Attribution correction stands: the regression was #794, not #811 (this issue's original bisect had a never-green 'good' endpoint). The regression-probe blind spot that hid #794's breakage is closed by #845. Verified on main: the failing startRun test passes; descriptor test family 4/4.
