### PR TITLE
One-off ponytail simplification pass (~-220 lines of copy-pasted helpers)

### LINKED ISSUE #791: Run a ponytail simplification pass on main before v0.1.0 work
## Context

Maintainer decision (2026-08-24): before any other v0.1.0 milestone work, run a [ponytail](https://ponytail.dev/) simplification pass across main to reduce code and improve maintainability.

ponytail is a ruleset/plugin for coding agents ("write the least code that works"): does it need to exist → reuse what's already in the codebase → stdlib → native platform feature → already-installed dependency → one line → only then the minimum code. Validation, error handling, security, and accessibility are explicitly never simplified away.

## Tasks

- [ ] One-off execution only (maintainer decision 2026-08-24): apply the [ponytail ruleset](https://github.com/DietrichGebert/ponytail/blob/main/.agents/rules/ponytail.md) as the working rules for this single pass — do **not** install the plugin into the repo or commit the ruleset
- [ ] Run a repo-wide simplification pass on main, package by package
- [ ] Land as reviewed PRs — no behavior changes; CI green per PR
- [ ] After the pass: full test suite plus one local default-profile smoke E2E

## Notes

- Runs immediately after #792 (maintainer re-order 2026-08-24): #792 lands first since it removes/simplifies code this pass would otherwise churn on. This issue is its follow-up PR; the rest of the milestone follows.
- Related: #462 (Refactor/simplify codebase) — this is the concrete execution vehicle for it; #462 stays open for anything the pass doesn't reach.

### PR DESCRIPTION
**Pull request by aviggiano**
Closes #791.

One-off ponytail execution over main (per the issue: single pass, no plugin install, no committed ruleset). Rules applied: reuse what exists → stdlib → one line → deletion over addition; validation, error handling, and security checks untouched. Stacked on #807's branch history.

## What changed (~58 files, net ≈ −220 lines)

**New `packages/artifacts/src/lang-primitives.ts`** — the one shared home for primitives every package had copy-pasted (every package already depends on `@ultrafuzz/artifacts`):
- `isRecord` — was 31 byte-identical copies; 25 removed. Kept local: the 6 guarded copies in sealed/gate/authority modules (deliberate — see below), plus two type-alias variants (`dashboard/index.ts` narrows to `JsonObject`, `final-report-markdown.ts` to `JsonRecord`).
- `sameStrings` — 5 copies → 1.
- `errorMessage` — 4 identical helper definitions → 1 (the ~140 inline uses of the same idiom are untouched: churn with zero line delta).
- `jsonPointerPath` — 3 byte-identical 15-liners inside artifacts → 1.
- `canonicalJsonValueKey` — 2 semantically-identical copies inside artifacts → 1.

**Stdlib over hand-rolled:**
- `lstatIfPresent` ×6 → one-line `fs.lstatSync(path, { throwIfNoEntry: false })` (suppresses exactly ENOENT, same as every removed try/catch; the `runtime/init.ts` bigint variant keeps `bigint: true`).
- `sleep`/`wait` ×7 → `import { setTimeout as sleep } from "node:timers/promises"` (the pattern `npm-install-retry.ts` already used).

**Intra-package dedup / drift-risk fixes:**
- `tomlString` ×3 → exported once from `modal/workspace-config.ts`.
- Modal's two hardcoded `["succeeded","failed","timed-out","canceled"]` terminal-status lists now read `TERMINAL_RUN_STATE_STATUSES` from artifacts (kills a real drift risk; local `string | undefined` signatures kept).
- `runtime`'s `VULNERABILITY_DATABASE_CATALOG_PATH` is now an alias of references' `VULNERABILITY_DATABASE_CATALOG_ARTIFACT_PATH` instead of a re-declared literal.
- `dashboard/package.json`: removed the `@ultrafuzz/security` dependency (zero imports anywhere in the package).

## What was deliberately NOT touched

- **Guarded code:** anything sealed/authority/gate-named (`sealed-schema-registry`, `semantic-gates`, `artifact-gates`, `smithers-attempt-authority`, `verified-output`, `workflow-integrity`) keeps its local copies — redundancy at a trust boundary is not fat.
- **Validator-identity-frozen modules:** the five modules hashed into `VALIDATOR_BUILD_IDENTITY` (`json-file-validator`, `json-schema-validator`, `json-validation-worker`, `schema-registry`, `strict-json`). An early version of this pass deduped two of them and rotated the identity, tripping the #787 pin ("a compatibility-only bundle loader must retain the pre-upgrade validator identity") — reverted; the identity is byte-identical to main (`…9674a6d4`), verified at runtime.
- Same-name-different-contract families (`recordField`/`stringField`/`nonEmptyString` variants), the canonicalize/fingerprint family (feeds sealed digests), the pinned-DNS `https.request` in `model-pricing.ts` (deliberate SSRF defense), one-impl interfaces with test doubles, and the oclif alias command files documented in the CLI docs.

## Validation

- Per-package suites (this branch): config 72/72 · topology 69/69 · prompts 102/102 · dashboard 35/35 · evals 426/426 · modal 629/629 · cli 161/161 · artifacts 315/316 (the one failure is the pre-existing atomic-replacement flake noted on #807) · runtime: see checklist comment (same pre-existing #779 set as #807)
- `pnpm -w build`, `pnpm -w typecheck`, `pnpm lint`, `pnpm format:check`, `pnpm docs:check`, `node scripts/validate-audit-profile-package.mjs` — all green
- `VALIDATOR_BUILD_IDENTITY` verified equal to main's pinned value

🤖 Generated with [Claude Code](https://claude.com/claude-code)

<h3>Greptile Summary</h3>

This PR consolidates duplicated language helpers into `@ultrafuzz/artifacts` and replaces local filesystem, timer, status, TOML, and catalog-path helpers with equivalent shared or standard-library implementations.

- Adds and exports shared structural, comparison, error, JSON-pointer, and canonicalization primitives.
- Reuses those primitives across artifact, CLI, configuration, dashboard, evaluation, Modal, reference, runtime, and topology packages.
- Replaces hand-written sleep and optional-`lstat` wrappers with Node standard-library APIs.
- Centralizes Modal terminal statuses and TOML string serialization, and aliases the runtime vulnerability-catalog path to its reference contract.

<h3>Confidence Score: 5/5</h3>

The PR appears safe to merge because the consolidated helpers and standard-library replacements preserve the reviewed contracts and no actionable failures were identified.

The shared terminal-state and catalog-path values match their removed definitions exactly, helper implementations remain equivalent, and the new package imports have declared dependencies without a concrete initialization cycle.

<details><summary><h3>Important Files Changed</h3></summary>

| Filename | Overview |
|----------|----------|
| packages/artifacts/src/lang-primitives.ts | Introduces shared implementations equivalent to the removed local helpers; no behavioral regression was identified. |
| packages/artifacts/src/index.ts | Exposes the new primitives through the artifacts package’s existing public barrel without creating a consumer import cycle. |
| packages/modal/src/worker.ts | Reuses shared terminal-state, timer, and TOML helpers while preserving the previous lifecycle classifications and behavior. |
| packages/modal/src/resume.ts | Replaces the local terminal-status list with an identical shared status constant. |
| packages/runtime/src/vulnerability-database.ts | Reuses the references package’s byte-identical catalog path and the shared ordered-string comparator. |
| packages/evals/src/utils.ts | Re-exports the shared record predicate in place of its identical local implementation, preserving existing consumers. |
| packages/cli/src/commands/report/bundle.ts | Replaces the ENOENT-only `lstat` wrapper with Node’s equivalent `throwIfNoEntry: false` option. |

</details>

<sub>Reviews (1): Last reviewed commit: ["Apply a one-off ponytail simplification ..."](https://github.com/monad-developers/ultrafuzz/commit/c16297bbff4fd19e22cf17f49ac182d95db1bf57) | [Re-trigger Greptile](https://app.greptile.com/api/retrigger?id=56385581)</sub>

### CODE REVIEW

**Comment by aviggiano** [comment]
Post-rebase re-validation of this branch is complete. config 72/72, artifacts 316/316 (the atomic-replacement flake passed this round), runtime 952/1009 with **all 15 failures pre-existing on main**, verified two ways:

1. **14 relocated-cloud-worker failures** — #779 rewrote the generated workflow's module fallbacks to multiline `new URL(...)` expressions but `cloud-worker-harness.ts:79` still regexes the old single-line `?? "<string>"` form (also noted on #807).
2. **1 new failure: `startRun forwards cloud provider credentials through the Smithers environment filter`** — fails with `Cannot find module 'smthrs/jsx-dev-runtime'` from the sealed workflow. Deterministic (3/3) on a clean `origin/main` worktree too; `git bisect` between the #807 squash (good) and main HEAD names **8caf159f (#811 "Preserve fresh operator runner execution authority") as the first bad commit**.

Neither is touched by this branch.
