### ISSUE TITLE
Trusted CLI module confinement crashes on Bun (registerHooks is not a function)

### ISSUE THREAD

**Issue by aviggiano** [monad-developers/ultrafuzz#937]
## Summary

CI on `main` is red at `fca2551b332ff7776893d06e9ba4b53da1612fd1`. The job **Full release validation (Node.js 24 runtime support tests and Bun 1.3.14 adapter contracts)** fails one test:

```
(fail) Bun adapter contract: two active API-key providers reach generated children with only their own credential
 39 pass / 1 skip / 1 fail
```

Failing run: https://github.com/monad-developers/ultrafuzz/actions/runs/32973847032 (job 98195406016)

## Root cause

`trustedCliModuleConfinementSource()` in `packages/runtime/src/trusted-cli-closure.ts` emits a `module-confinement.cjs` whose only enforcement mechanism is `require("node:module").registerHooks`. The trusted CLI launcher (`packages/runtime/src/trusted-cli.ts`) then executes the closure entrypoint as

```
process.execPath --no-global-search-paths --import <module-confinement.cjs> <cli entrypoint> ...
```

`registerHooks` is a Node-only synchronous loader-hooks API. **Bun 1.3.14 does not implement it**, so when `process.execPath` is `bun` — which is exactly the case under `bun test dist-test/test/runtime.test.js`, the Bun adapter contract lane — the shim throws before the CLI runs:

```
TypeError: registerHooks is not a function. (In 'registerHooks({ ... })', 'registerHooks' is undefined)
  at .../trusted-cli-closures/.tmp-.../module-confinement.cjs:21:1
```

which surfaces to the test as:

```
WORKFLOW_SUBMISSION_FAILED: workflow runner command failed
```

The confinement shim was introduced by #900 (`1f042ec6`, "Seal trusted CLI transitive execution identity"). Its Node-only mechanism was not gated on the host runtime, so it hard-crashes the trusted CLI on Bun. The Node.js integration shards all pass — only the Bun lane is affected.

## Fix direction

Make the emitted shim runtime-aware and **fail-closed on both runtimes**, keeping the Node path exactly as-is:

- Node: `registerHooks({ resolve, load })` as today, and throw if `registerHooks` is not a function rather than silently running unconfined.
- Bun: register a `bun` `plugin()` with an `onLoad` filter matching every `file`-namespace path *outside* the closure root and reject it — the same mechanism already used and reviewed for `BUN_MODULE_CONFINEMENT_SOURCE` in `packages/runtime/src/workflow-integrity.ts`.

Verified locally against Bun 1.3.14 that this preserves full parity with the Node checks: Bun hands `onLoad` the **realpath-resolved** path, so a symlink planted inside the closure that points outside is rejected too, and legitimate intra-closure `require`s are untouched (Bun has no `onLoad` fall-through — returning `undefined` raises `onLoad() expects an object returned` — so the negative-lookahead filter is the correct shape).

The rejection message stays `trusted CLI module resolved outside its content-addressed closure: <path>`, which is what `packages/runtime/test/trusted-cli.test.ts` asserts.

## Not a weakening

Confinement is *added* where there is currently none (the process cannot start at all on Bun today), and no Node-side check is relaxed.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
